root: true

parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  parser: babel-eslint

env:
  node: true
  es6: true
  browser: true
  jest: true
  jquery: true

extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'

rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  no-unused-vars: warn
  no-console: 'off'
  comma-style:
    - warn
    - last
  prefer-const: warn
  no-var: error
  eqeqeq: error

globals:
  blessing: false
  __bs_data__: false
