root: true

parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  parser: babel-eslint

env:
  node: true
  es6: true
  browser: true
  jest: true
  jquery: true

extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'

rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  no-unused-vars: warn
  no-console: 'off'
  comma-style:
    - warn
    - last
  prefer-const: warn
  no-var: error
  eqeqeq: error
  vue/html-closing-bracket-newline:
    - error
    - singleline: never
      multiline: always
  vue/html-indent:
    - error
    - 4
  vue/max-attributes-per-line:
    - error
    - singleline: 3
      multiline: 1
  vue/mustache-interpolation-spacing: error
  vue/no-multi-spaces: error
  vue/v-bind-style: error
  vue/v-on-style: error
  vue/html-quotes: error
  vue/order-in-components: warn

globals:
  blessing: false
  __bs_data__: false
